name: "Ask for Help"
description: "Need help with StatusPulse? Ask your questions here."
labels: ["help"]

body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please search [existing issues](https://github.com/TheSnakeByte/StatusPulse/issues?q=is%3Aissue) to see if your question has already been answered.
        Provide as much detail as possible to help others understand and assist you.

  - type: textarea
    id: description
    attributes:
      label: "Describe the Problem"
      description: "A clear and concise description of what you need help with."
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "State the operating system you are running StatusPulse on."
      placeholder: "E.g. Debian 12 (Bookworm), 64-bit"
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: "Node.js Version"
      description: "Run `node -v` to find your Node.js version."
      placeholder: "E.g. v20.8.0"
    validations:
      required: true

  - type: input
    id: statuspulse_version
    attributes:
      label: "StatusPulse Version"
      description: "Run `npm run version` in your StatusPulse directory to find the version."
      placeholder: "E.g. v1.0.0"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: "Browser"
      description: "(If applicable)"
      placeholder: "E.g. Google Chrome v133.0.6943.141"

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Optional. If applicable, state any other relevant context/details."
