name: "Feature Request"
description: "Suggest a possible feature for StatusPulse"
labels: ["feature request"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! Please fill out the details below.  
        Before subdcom/TheSnakeByte/StatusPulse/issues?q=label%3A%22feature%20request%22) to see if this request has already been suggested.
        Please also ensure that you have checked this feature does not exist in the latest version of StatusPulse.

  - type: textarea
    id: feature_description
    attributes:
      label: "Describe the Feature"
      description: "A clear and concise description of what the feature is."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Optional. If applicable, state any other relevant context/details."
