name: "Security Issue"
description: "Report a vulnerability that affects the security of StatusPulse."
labels: ["security"]

body:
  - type: markdown
    attributes:
      value: |
        ## Reporting Security Vulnerabilities 🔒  
        
        If you've found a security vulnerability in StatusPulse, **please do not open a public issue**.  
        
        Instead, report it privately via [GitHub's Security Advisory](https://github.com/TheSnakeByte/StatusPulse/security/advisories) to ensure responsible disclosure.  
        
        Thank you for helping keep StatusPulse secure!  

  - type: input
    id: hidden_field
    attributes:
      label: "Ignore this field"
      value: "Security report redirected to private disclosure."
    validations:
      required: true
