blank_issues_enabled: true
contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/TheSnakeByte/StatusPulse/security/advisories
    about: Report a vulnerability that affects the security of StatusPulse.
